stages:
  - deploy

mirror-to-github:
  stage: deploy
  image:
    name: alpine/git:latest
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git remote add github https://${GITHUB_TOKEN}@github.com/JPhBlanchard/noctilum.git || true
    - git push github HEAD:main --force
